### ISSUE TITLE
Would love to get the apk file from this.

### ISSUE THREAD

**Issue by ALinkToTao** [nivieru/ebookdroid#2]
I am kind of a newbie with all of this stuff, and I've been using the ebookdroid app, and I've really been loving it, but I thought it could really use some e-ink optimization.  Lo and behold, I googled your github project, and it turns out, you have already done it.  Is there a way someone could send me this project in the form of an installable apk file so that I may install it on my Nook Simple Touch?  Thank you so much!

**Comment by nivieru** [comment]
Hi ALinkToTao, Thanks for your interest.
You can now get the apk from the releases tab, [here](https://github.com/nivieru/ebookdroid/releases).
I havn't used my NST in almost two years, so I was glad to see that it still works (after recharging overnight), and also that this stuff is still useful for other people.

**Comment by nivieru** [comment]
Hi AlinkToTao, thanks for your interest. You can get it https://www.dropbox.com/s/vgnulbrtwr2vi6a/EBookDroid-nivieru.apk?dl=0

**Comment by ALinkToTao** [comment]
I thank you so much.  I've been rooting Nook Simple Touches for my friends and family and loading a bunch of books that I think they will like on there.  This will be a great addition for my comics I have in PDF format.  I thank you so much for your response.

**Comment by ALinkToTao** [comment]
Nivieru, I must say-greay work! This is everything I wanted in a pdf reader! You've really significantly improved the visual quality on the NST! Thank you so much! Long live the NST and your app!

**Comment by ALinkToTao** [comment]
If you don't mind, I'd love to post a link to download your app on xda developers and highlight your wonderful app there.  I'm sure you'd love to share your wonderful work.

Thanks again.

**Comment by nivieru** [comment]
Sure, go ahead.
Just to be clear though, I'm not the developer of EbookDroid, I just tweaked it a little.
